// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApyHzi4LQ3jvfFsJRCs4eSyOS7qfZoKcQ',
    appId: '1:548421416820:web:6b19804ddc8f9d61855e21',
    messagingSenderId: '548421416820',
    projectId: 'edu-vista-5abfd',
    authDomain: 'edu-vista-5abfd.firebaseapp.com',
    storageBucket: 'edu-vista-5abfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDSC08ROOn2O3D6lw1hIu4dZzcmNAGYxU',
    appId: '1:548421416820:ios:235b3b4d235119a5855e21',
    messagingSenderId: '548421416820',
    projectId: 'edu-vista-5abfd',
    storageBucket: 'edu-vista-5abfd.appspot.com',
    iosBundleId: 'com.example.usingFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDSC08ROOn2O3D6lw1hIu4dZzcmNAGYxU',
    appId: '1:548421416820:ios:235b3b4d235119a5855e21',
    messagingSenderId: '548421416820',
    projectId: 'edu-vista-5abfd',
    storageBucket: 'edu-vista-5abfd.appspot.com',
    iosBundleId: 'com.example.usingFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApyHzi4LQ3jvfFsJRCs4eSyOS7qfZoKcQ',
    appId: '1:548421416820:web:f6f53801a92a1787855e21',
    messagingSenderId: '548421416820',
    projectId: 'edu-vista-5abfd',
    authDomain: 'edu-vista-5abfd.firebaseapp.com',
    storageBucket: 'edu-vista-5abfd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdQAUNa_LlwLoErMQJv9aIGqhOFFvrmf4',
    appId: '1:548421416820:android:921944a4e07833d4855e21',
    messagingSenderId: '548421416820',
    projectId: 'edu-vista-5abfd',
    storageBucket: 'edu-vista-5abfd.appspot.com',
  );

}